[versions]
kotlin = "1.9.0"
lint = "31.2.2"


[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }


# Dependencies of the included build-logic

[plugins]
