[versions]
kotlin = "1.8.20"
lint = "30.4.2"


[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }


# Dependencies of the included build-logic

[plugins]
